[workspace]
members = [
    "crates/radium",
    "crates/radium-api",
    "crates/radium-bootstrapper",
]

# Better performance with color-eyre
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
