[workspace]
members = ["crates/radium", "crates/radium-hooking"]

[profile.dev]
panic = "abort"

# Better performance with color-eyre
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
