# Formatting will silently fail if rustfmt fails to reduce a string's width
format_strings = true

# Preference
format_code_in_doc_comments = true
fn_call_width = 80
imports_granularity = "Item"
wrap_comments = true
