[package]
name = "speng-radium-hooking"
version = "0.0.0"
edition = "2021"

[dependencies]
hashbrown = "0.13.2"
once_cell = "1.17.1"
parking_lot = "0.12.1"
region = "3.0.0"
thiserror = "1.0.39"
tracing = "0.1.37"

[dependencies.iced-x86]
version = "1.18.0"
features = ["code_asm"]
